<?php $helper = Mage::helper("flashy"); ?>

<?php if( $helper->getFlashyId() ) : ?>
	<script type="text/javascript">
		//<![CDATA[
			'use strict'; (function (a, b, c) { if (!a.flashy) { a.flashy = function () { a.flashy.event && a.flashy.event(arguments), a.flashy.queue.push(arguments) }, a.flashy.queue = []; var d = document.getElementsByTagName('script')[0], e = document.createElement(b); e.src = c, e.async = !0, d.parentNode.insertBefore(e, d) } })(window, 'script', 'https://js.flashyapp.com/thunder.js'), flashy('init', <?php echo $helper->getFlashyId(); ?>);
			flashy('PageView');

			<?php
				$flashy_id = Mage::getSingleton('core/cookie')->get('flashy_id');
                $customer = Mage::getSingleton('customer/session')->getCustomer();

				if( Mage::getSingleton('customer/session')->isLoggedIn() && (!$flashy_id || $flashy_id != base64_encode($customer->getEmail()))) { ?>

                    flashy('setCustomer', {
						"email": "<?php echo base64_encode($customer->getEmail()); ?>"
					});

			<?php } ?>
		//]]>
	</script>

	<?php if( $helper->getCart() ) : ?>
		<script type="text/javascript">
			//<![CDATA[
				<?php
					$cart_cache = Mage::getSingleton('core/cookie')->get('flashy_cart_cache');
					if( base64_encode($helper->getCart()) !== $cart_cache ) : ?>
						flashy('UpdateCart', <?php echo $helper->getCart(); ?>);
			    		<?php
			    		Mage::getSingleton('core/cookie')->set('flashy_cart_cache', base64_encode($helper->getCart()), 86400, '/');
			    	endif; ?>
			//]]>
		</script>
	<?php endif; ?>

<?php endif; ?>